### ISSUE TITLE
Nodes cannot be rendered.

### ISSUE THREAD

**Issue by xuyaqist** [ZJUVAG/NetV.js#144]
When I tried to use this d3-force [demo](https://netv.zjuvag.org/component/layout.html#d3-js-%E5%A4%96%E9%83%A8%E5%B8%83%E5%B1%80) in our dataset(114 nodes, 183 edges). The nodes cannot be rendered, like this. 
![image](https://user-images.githubusercontent.com/25164823/138701825-d3596f3c-4afe-406e-bfc9-d4f863cdd859.png)
And the error was like this.
![image](https://user-images.githubusercontent.com/25164823/138701948-368f3905-bec7-4812-85fe-ab1587da5a0b.png)

However, it's fine when the size of the node is smaller than 100.

**Comment by JackieAnxis** [comment]
Sorry for the late reply, I think maybe the type of your node ID is not allowed, only string & number are allowed. Maybe you should check the type of your node ID.

**Comment by JackieAnxis** [comment]
I'm sorry for the late reply. I'll check it soon.
If possible, may I have your dataset?
I believe some ID of your nodes may evoke the error.

**Comment by JackieAnxis** [comment]
If possible, may I have your dataset?

**Comment by xuyaqist** [comment]
> I'm sorry for the late reply. I'll check it soon

It's actually because you've set the nodeLimit and linkLimit in your code. When I change this part, the nodes render well.
![image](https://user-images.githubusercontent.com/25164823/142989181-670dd504-5b92-44f2-8288-55ae3e379e6f.png)

**Comment by JackieAnxis** [comment]
> > I'm sorry for the late reply. I'll check it soon
> 
> It's actually because you've set the nodeLimit and linkLimit in your code. When I change this part, the nodes render well. ![image](https://user-images.githubusercontent.com/25164823/142989181-670dd504-5b92-44f2-8288-55ae3e379e6f.png)

Thanks for your reply, maybe we shoule improve the nodeLimit&linkLimit into a bigger number in the future.

**Comment by JackieAnxis** [comment]
> > > I'm sorry for the late reply. I'll check it soon
> > 
> > 
> > It's actually because you've set the nodeLimit and linkLimit in your code. When I change this part, the nodes render well. ![image](https://user-images.githubusercontent.com/25164823/142989181-670dd504-5b92-44f2-8288-55ae3e379e6f.png)
> 
> Thanks for your reply, maybe we shoule improve the nodeLimit&linkLimit into a bigger number in the future.

@xuyaqist it is fixed.
