### ISSUE TITLE
Does NeV.js support data updates?

### ISSUE THREAD

**Issue by xuyaqist** [ZJUVAG/NetV.js#146]
When I update the data, for example, add a node or delete the node, and try to rebind the data, it will report the error "Cannot read properties of undefined(reading 'id')". 
So the only thing I can do is to retain the location of every node and new another netv to bind the updated data and set those nodes' locations, to make the layout look like it's updated. It's a little bit complicated though. 
I was wondering whether this problem can be solved by supporting the data updates in NetV.js? So I could just directly rebind the data instead of renewing a netv and set node position etc.

**Comment by JackieAnxis** [comment]
Thanks for your issue.
Deleting nodes/links is not supported in NetV.js yet. 
However, adding and changing nodes/links are supported.
For example, in this example: https://codepen.io/mgzx/pen/mdrLWRr, you can append these two lines of code in the end: 
```js
netv.addNode({id: 5, x: 10, y: 10})
netv.draw()
```
netv will draw another node:
![image](https://user-images.githubusercontent.com/19246028/143003740-01708b09-b560-4b8a-8126-b90bce2c3d0e.png)

If possible, a piece of code or gist will help me a lot to fix your problem.

**Comment by xuyaqist** [comment]
![image](https://user-images.githubusercontent.com/25164823/143233120-f003417a-ac25-4742-a00a-f5b4561988e2.png)

code: https://codepen.io/xuyaqist/pen/abyrKaL
For example, when I add a node while using a d3 force layout, it just adds the node in canvas. The layout didn't update(recalculate the force in d3). Besides, it seems like the redrawing has some problems too. 
Will NetV.js ever support the d3 force layout updates, not just simply redraw?

**Comment by JackieAnxis** [comment]
I'll check it soon in tomorrow morning
BTW, we are developping the layout plugin now...
As for the layout algorithm, we have published a new library ogdf.js, it contains several fast layout algorithms...
Unfortunately, we have not maintained a stable version yet...But you can still try it.

**Comment by JackieAnxis** [comment]
Manipulating a force-directed layout is not our currently focused task.
After I checked your code, I believe you need to update the force simulation like [demo-1](http://bl.ocks.org/sebbacon/6138241) and [demo-2](http://bl.ocks.org/rkirsling/5001347).
Hope it will help

**Comment by xuyaqist** [comment]
The two demos you referred to are great, and it works when I simply use d3.js force simulation. However, updating the force simulation needs an update of the dataset. 
`simulation.nodes(data.nodes).force('link').links(data.links);`
In NetV.js, every time when I try to update the dataset, for example, push a node into the data.nodes, it will report some errors.
![image](https://user-images.githubusercontent.com/25164823/143571975-21c60925-0bb1-419b-96cf-045ae98d311c.png)
Am I not supposed to update the dataset in NetV.js?

**Comment by JackieAnxis** [comment]
Sorry for the late reply.
I believe it is not a bug of NetV.js. It is caused by d3-force.
I simply wrote a [demo](https://codesandbox.io/s/d3-force-random-data-n7qxq?file=/force.js) to demonstrate that before your draw your new data, you should stop old simulation:

![image](https://user-images.githubusercontent.com/19246028/143971397-a4f6f0ce-497e-4251-b1c9-e29e854dbc0e.png)
