### ISSUE TITLE
multipule Link is not allowed.

### ISSUE THREAD

**Issue by Dreamerryao** [ZJUVAG/NetV.js#150]
Hello, I found that I can't create nodes A and B to reference each other when using netv.js. 
`Multiple link (a<=> b) is not allowd.` message is displayed.   Why is it prohibited?

**Comment by JackieAnxis** [comment]
The only reason is that Multiple Link is not supported now. 
We would like to support multiple link, but drawing those links from same nodes requires specific visual design.
For example, drawing multiple links from same nodes by different curve:
![image](https://github.com/ZJUVAI/NetV.js/assets/19246028/fcc9f46b-6091-4fb5-8731-f7a138fe0c4d)
Or drawing multiple straight links:
![image](https://github.com/ZJUVAI/NetV.js/assets/19246028/9de5efc2-0417-471b-ae20-70551cc70fa1)

It depends on users, we do not want to limit to a specific visual design.
