### ISSUE TITLE
Shader Compile Error 

### ISSUE THREAD

**Issue by Gykonik** [ZJUVAG/NetV.js#152]
When I try to run NetV.js or any of the demos on https://netv.zjuvag.org/component/, I always get the following error:

![image](https://user-images.githubusercontent.com/17333876/235518394-c613b445-f849-4c8a-89b9-892b50580b12.png)

Am I the only one? :D

**Comment by JackieAnxis** [comment]
Thanks and sorry for the late reply, now it is fixed by: ec0f2ff12cc9d350682f7a751c083170c1c5863d
